# Generated by Django 2.2.4 on 2019-08-29 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('length', models.CharField(max_length=100)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.Land')),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diameter', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=100)),
                ('health', models.CharField(max_length=100)),
                ('year', models.DateField()),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.Plot')),
            ],
        ),
    ]
